export const CameraConfig = {
  FOV: 45,
  NEAR: 0.1,
  FAR: 2000,
  BASE_Y: 3,
  BASE_Z: 8,
  LOOK_AT_Y: 1,
  MIN_VISIBLE_HALF_WIDTH: 2.2,
  SPRING_STIFFNESS: 200,
  SPRING_DAMPING: 28,

  ZOOM_IN_AMOUNT: 2,
  ZOOM_IN_DELAY: 0.2,
  ZOOM_IN_DURATION: 0.15,
  ZOOM_OUT_DELAY: 0.25,
  ZOOM_OUT_DURATION: 0.4
} as const
