export const PhysicsConfig = {
  BASE_SCROLL_SPEED: 40,
  MAX_SPEED_MULTIPLIER: 5,
  COINS_PER_BOOST: 3,
  STREAKS_TO_MAX_SPEED: 10,
  BASE_COIN_POINTS: 5,
  OBSTACLE_SCROLL_FACTOR: 0.5,
  LANE_SWITCH_SPEED: 1.6,
  LANE_LEFT_X: -1.8,
  LANE_RIGHT_X: 1.8,
  LANE_LEAN_ANGLE: 0.1746,
  LANE_LEAN_SPEED_FACTOR: 1.3,
  DROP_START_Y: 5,
  GRAVITY: 20,

  CRASH_POP_VELOCITY: 6,
  CRASH_FALL_Y: -5,
  CRASH_SPIN_SPEED: 15,
  CRASH_EXIT_VELOCITY_X: 8,
  CRASH_EXIT_X: 6,

  COLLISION_SHRINK: 0.1,
  COLLECTION_EXPANSION: 0.15,

  INVINCIBILITY_DURATION_MS: 3000
} as const

export type PhysicsConfigType = typeof PhysicsConfig
