export const PhysicsConfig = {
  BASE_SCROLL_SPEED: 20,
  MAX_SPEED_MULTIPLIER: 5,
  SPEED_RAMP_DURATION: 120,
  OBSTACLE_SCROLL_FACTOR: 0.5,
  LANE_SWITCH_SPEED: 1.6,
  LANE_LEFT_X: -1.5,
  LANE_RIGHT_X: 1.5,
  LANE_LEAN_ANGLE: 0.1746,
  DROP_START_Y: 5,
  GRAVITY: 20,

  SHADOW_BASE_SCALE: 1.0,
  SHADOW_MIN_SCALE: 0.3,
  SHADOW_MAX_HEIGHT: 5,
  SHADOW_BASE_OPACITY: 0.3,

  CRASH_POP_VELOCITY: 6,
  CRASH_FALL_Y: -5,
  CRASH_SPIN_SPEED: 15,

  COLLISION_SHRINK: 0.1,
  COLLECTION_EXPANSION: 0.15
} as const

export type PhysicsConfigType = typeof PhysicsConfig
