export const PopupConfig = {
  POOL_SIZE: 10,
  TEXTURE_SIZE: 128,
  PIXEL_SIZE: 6,
  PLANE_WIDTH: 0.7,
  PLANE_HEIGHT: 0.7,
  FLOAT_DISTANCE: 0.5,
  LIFETIME: 1,
  START_OPACITY: 0.65,
  FADE_START_RATIO: 0.4,
  SPAWN_OFFSET_Y: 1.4,
  COLOR_OBSTACLE: '#ffffff',
  COLOR_COIN: '#ffd700',
  MAX_PREGENERATE_VALUE: 150
} as const
