import { PhysicsConfig } from './physics.config'

const LANE_DASH_LENGTH = 3
const LANE_DASH_GAP = 2
const EDGE_LINE_SEGMENT_LENGTH = 6

export const SpawnConfig = {
  FAR_BOUND_Z: -90,
  NEAR_BOUND_Z: 10,
  FAR_SPAWN_Z: -88,
  NEAR_SPAWN_Z: 8,

  ITEM_SPAWN_INTERVAL: 1.5,

  NEAR_OBJECTS_X: 7,

  LANE_DASH_LENGTH,
  LANE_DASH_GAP,
  LANE_DASH_WIDTH: 0.2,
  LANE_DASH_SPAWN_INTERVAL: (LANE_DASH_LENGTH + LANE_DASH_GAP) / PhysicsConfig.BASE_SCROLL_SPEED,

  EDGE_LINE_SEGMENT_LENGTH,
  EDGE_LINE_SPAWN_INTERVAL: EDGE_LINE_SEGMENT_LENGTH / PhysicsConfig.BASE_SCROLL_SPEED,

  SIGN_SPAWN_INTERVAL: 3.0,

  ROAD_WIDTH: 8,
  ROAD_LENGTH: 150
} as const

export type SpawnConfigType = typeof SpawnConfig
