export const SpawnConfig = {
  SPAWN_Z: -40,
  DESPAWN_Z: 10,

  OBSTACLE_MIN_SPAWN_INTERVAL: 1.2,
  OBSTACLE_MAX_SPAWN_INTERVAL: 2.5,
  POWERUP_SPAWN_INTERVAL: 5,

  NEAR_OBJECTS_X: 5,
  SIGN_COUNT: 1,

  LANE_DASH_LENGTH: 1,
  LANE_DASH_GAP: 2,
  LANE_DASH_WIDTH: 0.1,
  ROAD_WIDTH: 8,
  ROAD_LENGTH: 100
} as const

export type SpawnConfigType = typeof SpawnConfig
