export const SpawnConfig = {
  OBSTACLE_SPAWN_Z: -30,
  OBSTACLE_DESPAWN_Z: 5,
  OBSTACLE_MIN_SPAWN_INTERVAL: 1.2,
  OBSTACLE_MAX_SPAWN_INTERVAL: 2.5,
  POWERUP_SPAWN_INTERVAL: 5,

  DISTANT_BUILDINGS_X: 40,
  DISTANT_BUILDINGS_Z: -50,
  MID_BUILDINGS_X: 25,
  MID_BUILDINGS_Z: -35,
  NEAR_OBJECTS_X: 12,
  NEAR_OBJECTS_Z: -20,

  DISTANT_PARALLAX_SPEED: 0.1,
  MID_PARALLAX_SPEED: 0.25,
  NEAR_PARALLAX_SPEED: 0.5
} as const

export type SpawnConfigType = typeof SpawnConfig
